//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use migration::types::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub nano_id: NanoId,
    pub name: String,
    pub color: String,
    pub description_path: String,
    pub priority: Priority,
    pub created_at: DateTimeUtc,
    pub modified_at: DateTimeUtc,
    pub parent_group_id: Option<NanoId>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_group_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub group: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
