//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::types::*;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub nano_id: NanoId,
    pub name: String,
    pub description_path: String,
    pub priority: Priority,
    pub due: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub modified_at: DateTimeUtc,
    pub group_id: NanoId,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub group: HasOne<super::group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
