//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::prelude::Local;
use migration::types::*;
use sea_orm::ActiveValue::Set;
use sea_orm::entity::prelude::*;
use std::future::ready;
use std::pin::Pin;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub nano_id: NanoId,
    pub name: String,
    pub color: Color,
    pub priority: Priority,
    pub created_at: DateTime,
    pub modified_at: DateTime,
    #[sea_orm(unique)]
    pub zettel_id: NanoId,
    pub parent_group_id: Option<NanoId>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_group_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub group: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::task::Entity>,
    #[sea_orm(
        belongs_to,
        from = "zettel_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub zettel: HasOne<super::zettel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn before_save<'life0, 'async_trait, C>(
        mut self,
        _db: &'life0 C,
        insert: bool,
    ) -> Pin<Box<dyn Future<Output = Result<Self, DbErr>> + Send + 'async_trait>>
    where
        C: ConnectionTrait + 'async_trait,
        Self: Send + 'async_trait,
        'life0: 'async_trait,
    {
        let now = Local::now().naive_local();

        // set modified at
        self.modified_at = Set(now);

        // we set the timestamp to non-utc
        if insert && self.created_at.is_not_set() {
            self.created_at = Set(now);
        }

        if insert && self.nano_id.is_not_set() {
            self.nano_id = Set(NanoId::default());
        }
        Box::pin(ready(Ok(self)))
    }
}
