//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
#![expect(unused_imports)]

pub use super::group::Entity as Group;
pub use super::task::Entity as Task;
pub use super::zettel::Entity as Zettel;
