//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::types::*;
use sea_orm::ActiveValue::Set;
use sea_orm::entity::prelude::*;
use std::{future::ready, pin::Pin};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub nano_id: NanoId,
    #[sea_orm(unique)]
    pub name: String,
    pub color: Color,
    #[sea_orm(has_one)]
    pub group: HasOne<super::group::Entity>,
    #[sea_orm(has_many, via = "zettel_tag")]
    pub zettels: HasMany<super::zettel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn before_save<'life0, 'async_trait, C>(
        mut self,
        _db: &'life0 C,
        insert: bool,
    ) -> Pin<Box<dyn Future<Output = Result<Self, DbErr>> + Send + 'async_trait>>
    where
        C: ConnectionTrait + 'async_trait,
        Self: Send + 'async_trait,
        'life0: 'async_trait,
    {
        if insert && self.nano_id.is_not_set() {
            self.nano_id = Set(NanoId::default());
        }
        if insert && self.color.is_not_set() {
            self.color = Set(Color::default());
        }

        if let Set(ref mut name) = self.name
            && insert
        {
            *name = name.replace(' ', "_");
        }
        Box::pin(ready(Ok(self)))
    }
}
