//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::types::*;
use sea_orm::entity::prelude::*;
use sea_orm::ActiveValue::Set;
use std::future::ready;
use std::pin::Pin;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub nano_id: NanoId,
    pub name: String,
    pub priority: Priority,
    pub due: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub modified_at: DateTimeUtc,
    #[sea_orm(unique)]
    pub zettel_id: NanoId,
    pub group_id: NanoId,
    #[sea_orm(
        belongs_to,
        from = "group_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub group: HasOne<super::group::Entity>,
    #[sea_orm(
        belongs_to,
        from = "zettel_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub zettel: HasOne<super::zettel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {
    fn before_save<'life0, 'async_trait, C>(
        mut self,
        _db: &'life0 C,
        insert: bool,
    ) -> Pin<Box<dyn Future<Output = Result<Self, DbErr>> + Send + 'async_trait>>
    where
        C: ConnectionTrait + 'async_trait,
        Self: Send + 'async_trait,
        'life0: 'async_trait,
    {
        if insert && self.nano_id.is_not_set() {
            self.nano_id = Set(NanoId::default());
        }
        Box::pin(ready(Ok(self)))
    }
}
