//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "zettel_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub zettel_nano_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_nano_id: String,
    #[sea_orm(
        belongs_to,
        from = "tag_nano_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub tag: HasOne<super::tag::Entity>,
    #[sea_orm(
        belongs_to,
        from = "zettel_nano_id",
        to = "nano_id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub zettel: HasOne<super::zettel::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
